version: '3.3'

services:
  workspace:
    container_name: workspace
    build:
      dockerfile: Dockerfile
      context: ./workspace
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./../src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
      - php
    networks:
      - my-network

  nginx:
    container_name: nginx
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../src:/var/www/html
    depends_on:
      - mysql
      - php
    networks:
      - my-network

  php:
    container_name: php
    image: bitnami/php-fpm
    volumes:
      - ./../src:/var/www/html
      - ./php/conf.d/app.ini:/opt/bitnami/php/etc/conf.d/app.ini
    ports:
      - 9000:9000
    restart: always
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SEVICE_TAGS: dev
      SEVICE_NAME: mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - my-network

networks:
  my-network:

volumes:
  my-volume:
